title: The Gumtree Diaries
description: > # this means to ignore newlines until "baseurl:"
   Welcome to my blog! I'm an Australian developer embarking on a new adventure as I move to the UK. Follow along as I share my journey, thoughts on tech, coding projects, and the challenges of starting fresh in a new country.  
permalink: ':title/'
baseurl: ""
url: "https://efury1.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Eliza Fury
author-img: ElizaFury.jpg 
about-author: I am a full stack developer that is talking about their experience in and moving to the uk
social-twitter: FuryEliza
social-github: Efury1 
social-linkedin: eliza-fury-3004b3110/
social-email: ejfury@protonmail.com 

# Disqus
discus-identifier: mr-brown

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]